project_id = "cjulgfbmcnmrkvnzkpym"

[functions.discord-presence]
verify_jwt = false

[functions.report-user]
verify_jwt = false

[functions.record-view]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.generate-verification-code]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.admin-impersonate]
verify_jwt = true
