project_id = "cjulgfbmcnmrkvnzkpym"

[functions.share]
verify_jwt = false

[functions.og-embed]
verify_jwt = false

[functions.og-profile]
verify_jwt = false

[functions.debug-fetch]
verify_jwt = false

[functions.discord-presence]
verify_jwt = false

[functions.report-user]
verify_jwt = false

[functions.record-view]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.generate-verification-code]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.admin-update-profile]
verify_jwt = false

[functions.badge-request]
verify_jwt = false

[functions.bot-badge-requests]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.alias-request]
verify_jwt = false

[functions.x98zg89ezhg938g893g9389g3489g3894z]
verify_jwt = false

[functions.x809guj305gh9i00hezg890zu9ergo9ieuoh]
verify_jwt = false

[functions.x67ytf6t9f85hzohjoi90879sft7t623ui23u4g]
verify_jwt = false

[functions.verify-paypal-payment]
verify_jwt = false

[functions.get-paypal-config]
verify_jwt = false

[functions.send-premium-email]
verify_jwt = false

[functions.unban-user]
verify_jwt = false

[functions.receive-support-email]
verify_jwt = false

[functions.reply-support-email]
verify_jwt = false

[functions.admin-delete-account]
verify_jwt = false

[functions.assign-discord-role]
verify_jwt = false

[functions.assign-booster-badge]
verify_jwt = false

[functions.chat-ai]
verify_jwt = false

[functions.check-ban-status]
verify_jwt = false

[functions.api-proxy]
verify_jwt = false

[functions.ban-user]
verify_jwt = false

[functions.claim-support-ticket]
verify_jwt = false

[functions.get-user-email]
verify_jwt = false

[functions.og-html]
verify_jwt = false

[functions.record-link-click]
verify_jwt = false

[functions.send-email-change-code]
verify_jwt = false

[functions.submit-ban-appeal]
verify_jwt = false

[functions.verify-email-change]
verify_jwt = false

[functions.security-cleanup]
verify_jwt = false

[functions.mfa-verify]
verify_jwt = false
