project_id = "cjulgfbmcnmrkvnzkpym"

[functions.discord-presence]
verify_jwt = false

[functions.report-user]
verify_jwt = false

[functions.record-view]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.generate-verification-code]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.admin-update-profile]
verify_jwt = false

[functions.badge-request]
verify_jwt = false

[functions.bot-badge-requests]
verify_jwt = false

[functions.x98zg89ezhg938g893g9389g3489g3894z]
verify_jwt = false

[functions.x809guj305gh9i00hezg890zu9ergo9ieuoh]
verify_jwt = false

[functions.x67ytf6t9f85hzohjoi90879sft7t623ui23u4g]
verify_jwt = false

[functions.og-profile]
verify_jwt = false

[functions.share]
verify_jwt = false
